/** Error envelope and code → HTTP status mapping — design §5.2, §5.3. */

export const ERROR_CODES = [
  'UNAUTHENTICATED',
  'TOS_REQUIRED',
  'BETA_BLOCKED',
  'ONBOARDING_REQUIRED',
  'FORBIDDEN',
  'NOT_FOUND',
  'NO_PROMPT',
  'VALIDATION',
  'COPY_BLOCKED',
  'UNPUBLISHED',
  'SCORING_IN_PROGRESS',
  'QUOTA_EXCEEDED',
  'RATE_LIMITED',
  'LLM_TIMEOUT',
  'LLM_INVALID_SCHEMA',
  'PAYLOAD_TOO_LARGE',
  'INTERNAL',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

const HTTP_STATUS = {
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  PAYLOAD_TOO_LARGE: 413,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
} as const;

export const ERROR_HTTP_STATUS: Readonly<Record<ErrorCode, number>> = {
  UNAUTHENTICATED: HTTP_STATUS.UNAUTHORIZED,
  TOS_REQUIRED: HTTP_STATUS.FORBIDDEN,
  BETA_BLOCKED: HTTP_STATUS.FORBIDDEN,
  ONBOARDING_REQUIRED: HTTP_STATUS.FORBIDDEN,
  FORBIDDEN: HTTP_STATUS.FORBIDDEN,
  NOT_FOUND: HTTP_STATUS.NOT_FOUND,
  NO_PROMPT: HTTP_STATUS.UNPROCESSABLE_ENTITY,
  VALIDATION: HTTP_STATUS.UNPROCESSABLE_ENTITY,
  COPY_BLOCKED: HTTP_STATUS.UNPROCESSABLE_ENTITY,
  UNPUBLISHED: HTTP_STATUS.CONFLICT,
  SCORING_IN_PROGRESS: HTTP_STATUS.CONFLICT,
  QUOTA_EXCEEDED: HTTP_STATUS.TOO_MANY_REQUESTS,
  RATE_LIMITED: HTTP_STATUS.TOO_MANY_REQUESTS,
  LLM_TIMEOUT: HTTP_STATUS.BAD_GATEWAY,
  LLM_INVALID_SCHEMA: HTTP_STATUS.BAD_GATEWAY,
  PAYLOAD_TOO_LARGE: HTTP_STATUS.PAYLOAD_TOO_LARGE,
  INTERNAL: HTTP_STATUS.INTERNAL_SERVER_ERROR,
};

/** Every JSON error body — design §5.2. `message` is Vietnamese and user-displayable. */
export interface ApiErrorEnvelope {
  error: {
    code: ErrorCode;
    message: string;
    request_id: string;
    details?: Record<string, unknown>;
  };
}
